-- CreateTable
CREATE TABLE "IdentificazioneCliente" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "ragioneSociale" TEXT NOT NULL,
    "piva" TEXT NOT NULL,
    "via" TEXT NOT NULL,
    "cap" TEXT NOT NULL,
    "citta" TEXT NOT NULL,
    "contattoEmail" TEXT NOT NULL,
    "contattoTelefono" TEXT,
    "respNome" TEXT NOT NULL,
    "respCognome" TEXT NOT NULL,
    "respEmail" TEXT NOT NULL,
    "respTelefono" TEXT,
    "manutNome" TEXT NOT NULL,
    "manutCognome" TEXT NOT NULL,
    "manutEmail" TEXT NOT NULL,
    "manutTelefono" TEXT,
    "dittaAzienda" TEXT NOT NULL,
    "dittaEmail" TEXT NOT NULL,
    "dittaTelefono" TEXT NOT NULL,
    "tipoAttivita" TEXT NOT NULL,
    "numUtenti" INTEGER NOT NULL,
    "numPersonale" INTEGER NOT NULL,
    "tipoUtenti" TEXT NOT NULL,
    "repartiSpeciali" TEXT NOT NULL,
    "repartiSpecialiDettaglio" TEXT
);

-- CreateTable
CREATE TABLE "IdentificazioneStruttura" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "ragioneSociale" TEXT NOT NULL,
    "piva" TEXT NOT NULL,
    "indirizzo" TEXT,
    "citta" TEXT,
    "telefono" TEXT,
    "email" TEXT,
    "tipologiaStruttura" TEXT NOT NULL,
    "periodoEsercizio" TEXT NOT NULL,
    "valutazioneRischioLegionellosi" TEXT NOT NULL,
    "dataValutazione" TEXT,
    "noteValutazione" TEXT,
    "pianoGestioneRischio" TEXT NOT NULL,
    "notePianoGestione" TEXT,
    "campionamentiLegionella" TEXT NOT NULL,
    "noteCampionamenti" TEXT,
    "registroIgiene" TEXT NOT NULL,
    "noteRegistro" TEXT,
    "pc1" REAL,
    "pc2" REAL,
    "pc3" REAL,
    "pc4" REAL,
    "pc5" REAL,
    "tac1" REAL,
    "tac2" REAL,
    "tac3" REAL,
    "tac4" REAL,
    "tac5" REAL,
    "taf1" REAL,
    "taf2" REAL,
    "taf3" REAL,
    "taf4" REAL,
    "taf5" REAL,
    "cd1" REAL,
    "cd2" REAL,
    "cd3" REAL,
    "cd4" REAL,
    "cd5" REAL,
    "diff1" TEXT,
    "diff2" TEXT,
    "diff3" TEXT,
    "diff4" TEXT,
    "diff5" TEXT,
    "sistemaDisinfezione" TEXT NOT NULL,
    "noteDisinfezione" TEXT,
    "schedaSicurezza" TEXT,
    "noteSchedaSicurezza" TEXT,
    "sistemaControlloAutomatico" TEXT,
    "noteControlloAutomatico" TEXT
);
